[platformio]
src_dir = Source/Garage2
data_dir = Source/Garage2/data

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.filesystem = spiffs
board_build.partitions = default.csv
lib_deps =
	bblanchon/ArduinoJson @ ^7
	ESP32Async/ESPAsyncWebServer
	ESP32Async/AsyncTCP
